import React, { useEffect, useState } from "react";
import { API_KEY, IMG_URL } from "../../config/request";
import Head from "next/head";
import { useRouter } from "next/router";
import MediaCard from "../../core/components/MediaCard/MediaCard";
import S from "./movies.module.scss";

import useSWR from "swr";
import Pagination from "../../core/components/Filter/Pagination/Pagination";
import List_media from "../../core/components/List_media/List_media";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Media() {
  const router = useRouter();
  const [pagination, setPagination] = useState(1);
  const [slug, setSlug] = useState("movie");

  function getUrl(slug, page) {
    return `https://api.themoviedb.org/3/discover/${slug}?sort_by=popularity.desc&${API_KEY}&language=fr-FR&region=FR&page=${page}`;
  }

  const { data, error } = useSWR(getUrl(slug, pagination), fetcher);

  useEffect(() => {
    function getSlugWithNative() {
      const pathArray = window.location.pathname.split("/");
      return pathArray[pathArray.length - 1];
    }
    setSlug(getSlugWithNative());
    setPagination(1);
  }, [router.query.slug]);

  if (error) return <div>Failed to load</div>;

  return (
    <>
      <Head>
        <title>Prep academy - next - Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={S.movies_pages}>
        <Pagination callback={setPagination} page={pagination}></Pagination>
        {!data ? (
          <div>Loading ... </div>
        ) : (
          <List_media data={data}></List_media>
        )}
      </div>
    </>
  );
}
